<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Cover Letter - {{ $application->first_name }} {{ $application->last_name }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 13px; color: #1a1a1a; margin: 40px; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #1d4ed8; padding-bottom: 20px; }
        .header h1 { color: #1d4ed8; font-size: 26px; margin: 0; }
        .header p { color: #6b7280; margin: 5px 0 0; }
        .section { margin-bottom: 20px; }
        .section h2 { font-size: 14px; color: #1d4ed8; border-bottom: 1px solid #e5e7eb; padding-bottom: 5px; margin-bottom: 10px; text-transform: uppercase; letter-spacing: 0.05em; }
        table { width: 100%; border-collapse: collapse; }
        table td { padding: 6px 0; vertical-align: top; }
        table td:first-child { font-weight: bold; width: 140px; color: #374151; }
        table td:last-child { color: #1a1a1a; }
        .cover-letter-text { background: #f9fafb; border-left: 3px solid #1d4ed8; padding: 16px 20px; font-size: 13px; line-height: 1.7; color: #374151; white-space: pre-wrap; }
        .job-badge { display: inline-block; background: #eff6ff; color: #1d4ed8; padding: 4px 12px; border-radius: 4px; font-size: 12px; font-weight: bold; }
        .footer { margin-top: 40px; text-align: center; font-size: 11px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 15px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Janira Care</h1>
        <p>Job Application – Cover Letter</p>
    </div>

    <div class="section">
        <h2>Applicant Information</h2>
        <table>
            <tr>
                <td>Name</td>
                <td>{{ $application->first_name }} {{ $application->last_name }}</td>
            </tr>
            <tr>
                <td>Email</td>
                <td>{{ $application->email }}</td>
            </tr>
            <tr>
                <td>Phone</td>
                <td>{{ $application->phone }}</td>
            </tr>
            <tr>
                <td>Applied for</td>
                <td><span class="job-badge">{{ $application->job->title ?? 'N/A' }}</span></td>
            </tr>
            <tr>
                <td>Date</td>
                <td>{{ $application->created_at->format('d.m.Y') }}</td>
            </tr>
        </table>
    </div>

    <div class="section">
        <h2>Cover Letter</h2>
        <div class="cover-letter-text">{{ $application->cover_letter }}</div>
    </div>

    <div class="footer">
        Generated by Janira Care &bull; {{ now()->format('d.m.Y H:i') }}
    </div>
</body>
</html>
